-- add lifestyle columns to health_archive
ALTER TABLE health_archive
    ADD COLUMN smoking VARCHAR(32) DEFAULT NULL COMMENT '吸烟: NONE/QUIT/OCCASIONAL/REGULAR/HEAVY',
    ADD COLUMN drinking VARCHAR(32) DEFAULT NULL COMMENT '饮酒: NONE/QUIT/OCCASIONAL/REGULAR/HEAVY',
    ADD COLUMN sleep_quality VARCHAR(32) DEFAULT NULL COMMENT '熬夜: NEVER/RARELY/SOMETIMES/OFTEN/ALWAYS',
    ADD COLUMN exercise VARCHAR(32) DEFAULT NULL COMMENT '运动频率: NONE/ONCE_WEEK/2_3_WEEK/DAILY',
    ADD COLUMN diet VARCHAR(32) DEFAULT NULL COMMENT '饮食习惯: LIGHT/BALANCED/OILY/IRREGULAR',
    ADD COLUMN blood_sugar DECIMAL(5,2) DEFAULT NULL COMMENT '血糖(mmol/L)';
