FROM docker.m.daocloud.io/library/node:22-slim AS build
ENV VITE_API_BASE_URL=api
WORKDIR /frontend
COPY frontend/ .
RUN npm install -g pnpm && pnpm install && pnpm approve-builds && cd packages/web && npx vite build --config ./config/vite.config.prod.ts

FROM docker.m.daocloud.io/library/nginx:alpine
COPY --from=build /frontend/packages/web/dist /usr/share/nginx/html
COPY deploy/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
