FROM docker.m.daocloud.io/library/eclipse-temurin:21-jre
WORKDIR /app
COPY app-main.jar /app/app.jar
COPY commons-prod.properties /app/commons-prod.properties
EXPOSE 8081
ENTRYPOINT ["java", "-jar", "/app/app.jar", "--spring.profiles.active=prod", "--spring.config.additional-location=file:/app/commons-prod.properties"]
